name: Deploy Frontends to S3

on:
  push:
    branches:
      - main
    paths:
      - 'parent-client/**'
      - 'admin-client/**'
      - '.github/workflows/deploy_fe.yml'

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: us-east-1
  VITE_API_URL: https://service.draftedge.ai/api

jobs:
  deploy-parent:
    name: Build and Deploy Parent Client
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./parent-client

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: VITE_API_URL=${{ env.VITE_API_URL }} npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync ./dist s3://brightwheel-demo-client --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.CLIENT_DISTRIBUTION_ID }} \
            --paths "/*"

  deploy-admin:
    name: Build and Deploy Admin Client
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./admin-client

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: VITE_API_URL=${{ env.VITE_API_URL }} npm run build

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        run: aws s3 sync ./dist s3://brightwheel-demo-admin --delete

      - name: Invalidate CloudFront Cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ secrets.ADMIN_DISTRIBUTION_ID }} \
            --paths "/*"
